services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ratelimiter_network

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/.env
    depends_on:
      - redis
    networks:
      - ratelimiter_network

volumes:
  redis-data:

networks:
  ratelimiter_network:
    name: ratelimiter_network